Repository SENAC-ADS-1/e-commerce-dw-nv, pull requests merged in 2021-12, with the labels that each got.

#24 FEATURE: add sidebar, header and styles configs
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.scss
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/src/app/header/header.component.html
  frontend/src/app/src/app/header/header.component.scss
  frontend/src/app/src/app/header/header.component.ts
  frontend/src/app/src/app/sidebar/sidebar.component.html
  frontend/src/app/src/app/sidebar/sidebar.component.scss
  frontend/src/app/src/app/sidebar/sidebar.component.spec.ts
  frontend/src/app/src/app/sidebar/sidebar.component.ts
  frontend/src/index.html
  frontend/src/styles.css
  frontend/src/styles.scss
Labels: bug

#25 feature/categoria
  frontend/src/app/app.module.ts
  frontend/src/app/src/app/commons/models/pagination.model.ts
  frontend/src/app/src/app/commons/services/route.service.ts
  frontend/src/app/src/app/modules/categoria/categoria-routing.module.ts
  frontend/src/app/src/app/modules/categoria/categoria.module.ts
  frontend/src/app/src/app/modules/categoria/model/categoria.model.ts
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.html
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.scss
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.spec.ts
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.ts
  frontend/src/app/src/app/modules/categoria/service/categoria.service.spec.ts
  frontend/src/app/src/app/modules/categoria/service/categoria.service.ts
  frontend/src/app/src/app/sidebar/sidebar.component.html
Labels: enhancement

#27 BUG: change files to correct root. FEATURE: add categoria listar
  frontend/src/app/app.component.html
  frontend/src/app/app.component.scss
  frontend/src/app/app.module.ts
  frontend/src/app/commons/models/pagination.model.ts
  frontend/src/app/commons/services/route.service.ts
  frontend/src/app/header/header.component.html
  frontend/src/app/header/header.component.scss
  frontend/src/app/header/header.component.spec.ts
  frontend/src/app/header/header.component.ts
  frontend/src/app/modules/categoria.rar
  frontend/src/app/modules/categoria/categoria-routing.module.ts
  frontend/src/app/modules/categoria/categoria.module.ts
  frontend/src/app/modules/categoria/components/categoria-form/categoria-form.component.css
  frontend/src/app/modules/categoria/components/categoria-form/categoria-form.component.html
  frontend/src/app/modules/categoria/components/categoria-form/categoria-form.component.ts
  frontend/src/app/modules/categoria/model/categoria.model.ts
  frontend/src/app/modules/categoria/pages/categoria-atualizar/categoria-atualizar.component.css
  frontend/src/app/modules/categoria/pages/categoria-atualizar/categoria-atualizar.component.html
  frontend/src/app/modules/categoria/pages/categoria-atualizar/categoria-atualizar.component.ts
  frontend/src/app/modules/categoria/pages/categoria-cadastrar/categoria-cadastrar.component.css
  frontend/src/app/modules/categoria/pages/categoria-cadastrar/categoria-cadastrar.component.html
  frontend/src/app/modules/categoria/pages/categoria-cadastrar/categoria-cadastrar.component.ts
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.css
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.html
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.ts
  frontend/src/app/modules/categoria/pages/categoria-visualizar/categoria-visualizar.component.css
  frontend/src/app/modules/categoria/pages/categoria-visualizar/categoria-visualizar.component.html
  frontend/src/app/modules/categoria/pages/categoria-visualizar/categoria-visualizar.component.ts
  frontend/src/app/modules/categoria/service/categoria.service.ts
  frontend/src/app/sidebar/sidebar.component.html
  frontend/src/app/sidebar/sidebar.component.scss
  frontend/src/app/sidebar/sidebar.component.spec.ts
  frontend/src/app/sidebar/sidebar.component.ts
  frontend/src/app/src/app/header/header.component.html
  frontend/src/app/src/app/modules/categoria/categoria-routing.module.ts
  frontend/src/app/src/app/modules/categoria/categoria.module.ts
  frontend/src/app/src/app/modules/categoria/model/categoria.model.ts
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.html
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.spec.ts
  frontend/src/app/src/app/modules/categoria/pages/categoria-listar/categoria-listar.component.ts
  frontend/src/app/src/app/modules/categoria/service/categoria.service.spec.ts
  frontend/src/app/src/app/modules/categoria/service/categoria.service.ts
  frontend/src/index.html
Labels: bug, enhancement

#28 Feature/produtos
  frontend/src/app/app.module.ts
  frontend/src/app/modules/categoria/categoria.module.ts
  frontend/src/app/modules/produto/model/produto.model.ts
  frontend/src/app/modules/produto/pages/produto-lista/produto-lista.component.html
  frontend/src/app/modules/produto/pages/produto-lista/produto-lista.component.scss
  frontend/src/app/modules/produto/pages/produto-lista/produto-lista.component.spec.ts
  frontend/src/app/modules/produto/pages/produto-lista/produto-lista.component.ts
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.html
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.scss
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.spec.ts
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.ts
  frontend/src/app/modules/produto/produto-routing.module.ts
  frontend/src/app/modules/produto/produto.module.ts
  frontend/src/app/modules/produto/service/produto.service.spec.ts
  frontend/src/app/modules/produto/service/produto.service.ts
  frontend/src/app/sidebar/sidebar.component.html
Labels: enhancement

#29 Feature/categoria visualizar
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.html
  frontend/src/app/modules/categoria/pages/categoria-visualizar/categoria-visualizar.component.html
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.html
Labels: enhancement

#30 FEATURE: add atualizar, cadastrar e remover categoria
  frontend/src/app/modules/categoria/components/categoria-form/categoria-form.component.html
  frontend/src/app/modules/categoria/components/categoria-form/categoria-form.component.ts
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.css
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.html
Labels: enhancement

#33 feature/produto crud
  frontend/src/app/modules/categoria/model/categoria.model.ts
  frontend/src/app/modules/categoria/pages/categoria-cadastrar/categoria-cadastrar.component.ts
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.html
  frontend/src/app/modules/categoria/service/categoria.service.ts
  frontend/src/app/modules/produto/components/produto-form/produto-form.component.html
  frontend/src/app/modules/produto/components/produto-form/produto-form.component.scss
  frontend/src/app/modules/produto/components/produto-form/produto-form.component.spec.ts
  frontend/src/app/modules/produto/components/produto-form/produto-form.component.ts
  frontend/src/app/modules/produto/model/produto.model.ts
  frontend/src/app/modules/produto/pages/produto-atualizar/produto-atualizar.component.html
  frontend/src/app/modules/produto/pages/produto-atualizar/produto-atualizar.component.scss
  frontend/src/app/modules/produto/pages/produto-atualizar/produto-atualizar.component.spec.ts
  frontend/src/app/modules/produto/pages/produto-atualizar/produto-atualizar.component.ts
  frontend/src/app/modules/produto/pages/produto-cadastrar/produto-cadastrar.component.html
  frontend/src/app/modules/produto/pages/produto-cadastrar/produto-cadastrar.component.scss
  frontend/src/app/modules/produto/pages/produto-cadastrar/produto-cadastrar.component.spec.ts
  frontend/src/app/modules/produto/pages/produto-cadastrar/produto-cadastrar.component.ts
  frontend/src/app/modules/produto/pages/produto-lista/produto-lista.component.html
  frontend/src/app/modules/produto/pages/produto-lista/produto-lista.component.ts
  frontend/src/app/modules/produto/pages/produto-visualizar.rar
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.html
  frontend/src/app/modules/produto/pages/produto-visualizar/produto-visualizar.component.ts
  frontend/src/app/modules/produto/produto-routing.module.ts
  frontend/src/app/modules/produto/produto.module.ts
  frontend/src/app/modules/produto/service/produto.service.ts
Labels: enhancement

#34 feature/rotas-atualizacao-cliente
  backend/ecommerce/src/main/java/br/senac/devweb/api/ecommerce/cliente/ClienteController.java
  backend/ecommerce/src/main/java/br/senac/devweb/api/ecommerce/cliente/ClienteRepresentation.java
  backend/ecommerce/src/main/java/br/senac/devweb/api/ecommerce/cliente/ClienteService.java
  backend/ecommerce/src/main/java/br/senac/devweb/api/ecommerce/config/WebSecurityConfiguration.java
Labels: enhancement

#35 feature/cliente crud
  frontend/src/app/app.module.ts
  frontend/src/app/modules/categoria/pages/categoria-lista/categoria-lista.component.ts
  frontend/src/app/modules/cliente/cliente-routing.module.ts
  frontend/src/app/modules/cliente/cliente.module.ts
  frontend/src/app/modules/cliente/components/cliente-form/cliente-form.component.html
  frontend/src/app/modules/cliente/components/cliente-form/cliente-form.component.scss
  frontend/src/app/modules/cliente/components/cliente-form/cliente-form.component.spec.ts
  frontend/src/app/modules/cliente/components/cliente-form/cliente-form.component.ts
  frontend/src/app/modules/cliente/model/cliente.model.ts
  frontend/src/app/modules/cliente/pages/cliente-atualizar-senha/cliente-atualizar-senha.component.html
  frontend/src/app/modules/cliente/pages/cliente-atualizar-senha/cliente-atualizar-senha.component.scss
  frontend/src/app/modules/cliente/pages/cliente-atualizar-senha/cliente-atualizar-senha.component.spec.ts
  frontend/src/app/modules/cliente/pages/cliente-atualizar-senha/cliente-atualizar-senha.component.ts
  frontend/src/app/modules/cliente/pages/cliente-atualizar/cliente-atualizar.component.html
  frontend/src/app/modules/cliente/pages/cliente-atualizar/cliente-atualizar.component.scss
  frontend/src/app/modules/cliente/pages/cliente-atualizar/cliente-atualizar.component.spec.ts
  frontend/src/app/modules/cliente/pages/cliente-atualizar/cliente-atualizar.component.ts
  frontend/src/app/modules/cliente/pages/cliente-cadastrar/cliente-cadastrar.component.html
  frontend/src/app/modules/cliente/pages/cliente-cadastrar/cliente-cadastrar.component.scss
  frontend/src/app/modules/cliente/pages/cliente-cadastrar/cliente-cadastrar.component.spec.ts
  frontend/src/app/modules/cliente/pages/cliente-cadastrar/cliente-cadastrar.component.ts
  frontend/src/app/modules/cliente/pages/cliente-lista/cliente-lista.component.html
  frontend/src/app/modules/cliente/pages/cliente-lista/cliente-lista.component.scss
  frontend/src/app/modules/cliente/pages/cliente-lista/cliente-lista.component.spec.ts
  frontend/src/app/modules/cliente/pages/cliente-lista/cliente-lista.component.ts
  frontend/src/app/modules/cliente/service/cliente.service.spec.ts
  frontend/src/app/modules/cliente/service/cliente.service.ts
  frontend/src/app/sidebar/sidebar.component.html
Labels: enhancement

#36 bug/hotfix-cliente-cadastrar
  frontend/src/app/modules/categoria.rar
  frontend/src/app/modules/cliente/components/cliente-form/cliente-form.component.html
  frontend/src/app/modules/cliente/components/cliente-form/cliente-form.component.ts
  frontend/src/app/modules/cliente/pages/cliente-atualizar-senha/cliente-atualizar-senha.component.html
  frontend/src/app/modules/cliente/pages/cliente-atualizar/cliente-atualizar.component.html
  frontend/src/app/modules/cliente/pages/cliente-cadastrar/cliente-cadastrar.component.ts
Labels: enhancement
